version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oev-45plus-mail-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6dcwbg0gls89"
s3_prefix = "oev-45plus-mail-service"
region = "eu-central-1"
profile = "45plus"
capabilities = "CAPABILITY_IAM"
