AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  email-service

Parameters:
  Stage:
    Description: The stage of the api gateway
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - dev


Globals:
  Function:
    Timeout: 3

  Api:
    OpenApiVersion: 3.0.1
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:    
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Auth:
        ApiKeyRequired: true
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      StageKeys:
        - RestApiId: !Ref ApiGateway
          StageName: !Ref Stage
        
  MailFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: mail_service/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: SESSendMail
          Effect: Allow
          Action:
          - ses:SendEmail
          Resource: 'arn:aws:ses:eu-central-1:326094939662:identity/*'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /send_mail
            Method: POST
            