AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  email-service
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  MailFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: mail_service/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: SESSendMail
          Effect: Allow
          Action:
          - ses:SendEmail
          Resource: 'arn:aws:ses:eu-central-1:326094939662:identity/*'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /send_mail
            Method: POST